package Views.cliente;

import Views.direccion.*;
import crud.*;
import utilitarios.*;
import java.sql.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author micky
 */
public final class jfcliente extends javax.swing.JFrame {

    /**
     * Creates new form jfcliente
     */
    CUtilitarios cu = new CUtilitarios();
    CBusquedas cb = new CBusquedas();
    String seleccion, est, z, idZona, idEstatus, idEstatusAval;

    public jfcliente() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        cargaComboBox(jcbestatusbusqueda, 1);
        cargaComboBox(jcbnvestatuscliente, 1);
        //cargaComboBox(jcbnvestatuscliente, 1);
        //cargaComboBox(jcbestatuseli, 1);
        cargaComboBox(jcbnvestatusaval, 2);
        //cargaComboBox(jcbnvestatusaval, 2);
        cargaComboBox(jcbnvzona, 3);
        //cargaComboBox(jcbnvzona, 3);

        /* Placeholder JTField */
        cu.aplicarPlaceholder(jtfidbusqueda, "Ingresar ID");
        cu.aplicarPlaceholder(jtfnombresbusqueda, "Ingresar Nombre(s)");
        cu.aplicarPlaceholder(jtfapbusqueda, "Ingresar Apellido Paterno");
        cu.aplicarPlaceholder(jtfambusqueda, "Ingresar Apellido Maternos");
        cu.aplicarPlaceholder(jtfnvnombres, "Nombre(s)");
        cu.aplicarPlaceholder(jtfnvap, "Apellido Paterno");
        cu.aplicarPlaceholder(jtfnvam, "Apellido Materno");

        // Tablas
        cu.cargarTabla(jtlistaclienteaval);
    }

    private DefaultComboBoxModel listas;
    private ArrayList<String> datosListas = new ArrayList<>();
    private final CCargaCombos queryCarga = new CCargaCombos();

    public void cargaComboBox(JComboBox combo, int metodoCarga) {
        listas = (DefaultComboBoxModel) combo.getModel();
        try {
            switch (metodoCarga) {
                case 1:
                    datosListas = queryCarga.cargaComboEstatus();
                    for (int i = 0; i < datosListas.size(); i++) {
                        listas.addElement(datosListas.get(i));
                    }
                    datosListas.clear();
                    break;
                case 2:
                    datosListas = queryCarga.cargaComboEstatusAval();
                    for (int i = 0; i < datosListas.size(); i++) {
                        listas.addElement(datosListas.get(i));
                    }
                    datosListas.clear();
                    break;
                case 3:
                    datosListas = queryCarga.cargaComboZona();
                    for (int i = 0; i < datosListas.size(); i++) {
                        listas.addElement(datosListas.get(i));
                    }
                    datosListas.clear();
                    break;
            }
        } catch (SQLException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgnvestatus = new javax.swing.ButtonGroup();
        jpfondo = new javax.swing.JPanel();
        jLblIcono = new javax.swing.JLabel();
        jtppaneles = new javax.swing.JTabbedPane();
        jplistaclientes = new javax.swing.JPanel();
        jpfondotabla = new javax.swing.JPanel();
        jspclienteaval = new javax.swing.JScrollPane();
        jtlistaclienteaval = new javax.swing.JTable();
        jpfondobusqueda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfidbusqueda = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jtfnombresbusqueda = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jtfapbusqueda = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jtfambusqueda = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jcbestatusbusqueda = new javax.swing.JComboBox<>();
        jcbusuariobusqueda = new javax.swing.JComboBox<>();
        jpnuevocliente = new javax.swing.JPanel();
        jpfondonuevocliente = new javax.swing.JPanel();
        jtfnvnombres = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jtfnvap = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jtfnvam = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jcbnvzona = new javax.swing.JComboBox<>();
        jrbnvcliente = new javax.swing.JRadioButton();
        jrbnvaval = new javax.swing.JRadioButton();
        jrbnvambos = new javax.swing.JRadioButton();
        jcbnvestatuscliente = new javax.swing.JComboBox<>();
        jcbnvestatusaval = new javax.swing.JComboBox<>();
        jLblIcono1 = new javax.swing.JLabel();
        jbcontinuar = new javax.swing.JButton();
        jplistaclientes2 = new javax.swing.JPanel();
        jpfondotablaactyeli = new javax.swing.JPanel();
        jspclienteavalactyeli = new javax.swing.JScrollPane();
        jtlistaclienteavalactyeli = new javax.swing.JTable();
        jplistaclientes3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpfondo.setBackground(new java.awt.Color(242, 220, 153));
        jpfondo.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N

        jLblIcono.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cliente.png"))); // NOI18N
        jLblIcono.setText("  Clientes");

        jtppaneles.setBackground(new java.awt.Color(242, 220, 153));
        jtppaneles.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N

        jplistaclientes.setBackground(new java.awt.Color(242, 220, 153));
        jplistaclientes.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N

        jpfondotabla.setBackground(new java.awt.Color(242, 220, 153));

        jtlistaclienteaval.setBackground(new java.awt.Color(167, 235, 242));
        jtlistaclienteaval.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jtlistaclienteaval.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador", "Nombre(s)", "Apellido Paterno", "Apellido Materno", "Estatus"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtlistaclienteaval.setToolTipText("Listado de Clientes y Avales");
        jtlistaclienteaval.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jspclienteaval.setViewportView(jtlistaclienteaval);

        javax.swing.GroupLayout jpfondotablaLayout = new javax.swing.GroupLayout(jpfondotabla);
        jpfondotabla.setLayout(jpfondotablaLayout);
        jpfondotablaLayout.setHorizontalGroup(
            jpfondotablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpfondotablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspclienteaval, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpfondotablaLayout.setVerticalGroup(
            jpfondotablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpfondotablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspclienteaval, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpfondobusqueda.setBackground(new java.awt.Color(167, 235, 242));

        jLabel1.setBackground(new java.awt.Color(167, 235, 242));
        jLabel1.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Realiza Búsqueda");

        jtfidbusqueda.setBackground(new java.awt.Color(167, 235, 242));
        jtfidbusqueda.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jtfidbusqueda.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtfidbusqueda.setText("Ingresar ID");
        jtfidbusqueda.setToolTipText("Ingresar ID");
        jtfidbusqueda.setBorder(null);
        jtfidbusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setToolTipText("");

        jtfnombresbusqueda.setBackground(new java.awt.Color(167, 235, 242));
        jtfnombresbusqueda.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jtfnombresbusqueda.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtfnombresbusqueda.setText("Ingresar Nombre(s)");
        jtfnombresbusqueda.setToolTipText("Ingresar Nombre(s)");
        jtfnombresbusqueda.setBorder(null);
        jtfnombresbusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setToolTipText("");

        jtfapbusqueda.setBackground(new java.awt.Color(167, 235, 242));
        jtfapbusqueda.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jtfapbusqueda.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtfapbusqueda.setText("Ingresar Apellido Paterno");
        jtfapbusqueda.setToolTipText("Ingresar Apellido Paterno");
        jtfapbusqueda.setBorder(null);
        jtfapbusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setToolTipText("");

        jtfambusqueda.setBackground(new java.awt.Color(167, 235, 242));
        jtfambusqueda.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jtfambusqueda.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtfambusqueda.setText("Ingresar Apellido Materno");
        jtfambusqueda.setToolTipText("Ingresar Apellido Materno");
        jtfambusqueda.setBorder(null);
        jtfambusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setToolTipText("");

        jcbestatusbusqueda.setBackground(new java.awt.Color(167, 235, 242));
        jcbestatusbusqueda.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jcbestatusbusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estatus" }));
        jcbestatusbusqueda.setToolTipText("Selecciona un Estatus");
        jcbestatusbusqueda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jcbestatusbusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jcbusuariobusqueda.setBackground(new java.awt.Color(167, 235, 242));
        jcbusuariobusqueda.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jcbusuariobusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de Usuario" }));
        jcbusuariobusqueda.setToolTipText("Selecciona un tipo de Usuario");
        jcbusuariobusqueda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jcbusuariobusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jpfondobusquedaLayout = new javax.swing.GroupLayout(jpfondobusqueda);
        jpfondobusqueda.setLayout(jpfondobusquedaLayout);
        jpfondobusquedaLayout.setHorizontalGroup(
            jpfondobusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpfondobusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpfondobusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jcbusuariobusqueda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpfondobusquedaLayout.createSequentialGroup()
                        .addGroup(jpfondobusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfnombresbusqueda)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator1)
                            .addComponent(jtfidbusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addComponent(jtfambusqueda)
                            .addComponent(jSeparator4)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jtfapbusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addComponent(jcbestatusbusqueda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jpfondobusquedaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jSeparator1, jtfidbusqueda});

        jpfondobusquedaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jSeparator3, jtfapbusqueda});

        jpfondobusquedaLayout.setVerticalGroup(
            jpfondobusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpfondobusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jtfidbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtfnombresbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtfapbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtfambusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jcbestatusbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jcbusuariobusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jplistaclientesLayout = new javax.swing.GroupLayout(jplistaclientes);
        jplistaclientes.setLayout(jplistaclientesLayout);
        jplistaclientesLayout.setHorizontalGroup(
            jplistaclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplistaclientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpfondotabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jpfondobusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jplistaclientesLayout.setVerticalGroup(
            jplistaclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplistaclientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpfondotabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplistaclientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpfondobusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jtppaneles.addTab("Lista Clientes", jplistaclientes);

        jpnuevocliente.setBackground(new java.awt.Color(242, 220, 153));
        jpnuevocliente.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N

        jpfondonuevocliente.setBackground(new java.awt.Color(167, 235, 242));

        jtfnvnombres.setBackground(new java.awt.Color(167, 235, 242));
        jtfnvnombres.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jtfnvnombres.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtfnvnombres.setText("Nombre(s)");
        jtfnvnombres.setToolTipText("Nombre(s)");
        jtfnvnombres.setBorder(null);
        jtfnvnombres.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator6.setToolTipText("");

        jtfnvap.setBackground(new java.awt.Color(167, 235, 242));
        jtfnvap.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jtfnvap.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtfnvap.setText("Apellido Paterno");
        jtfnvap.setToolTipText("Apellido Paterno");
        jtfnvap.setBorder(null);
        jtfnvap.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator7.setToolTipText("");

        jtfnvam.setBackground(new java.awt.Color(167, 235, 242));
        jtfnvam.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jtfnvam.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtfnvam.setText("Apellido Materno");
        jtfnvam.setToolTipText("Apellido Materno");
        jtfnvam.setBorder(null);
        jtfnvam.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator8.setToolTipText("");

        jcbnvzona.setBackground(new java.awt.Color(167, 235, 242));
        jcbnvzona.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jcbnvzona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Zona" }));
        jcbnvzona.setToolTipText("Selecciona una zona");
        jcbnvzona.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jcbnvzona.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcbnvzona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbnvzonaActionPerformed(evt);
            }
        });

        bgnvestatus.add(jrbnvcliente);
        jrbnvcliente.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jrbnvcliente.setText("Cliente");
        jrbnvcliente.setToolTipText("Cliente");
        jrbnvcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbnvclienteActionPerformed(evt);
            }
        });

        bgnvestatus.add(jrbnvaval);
        jrbnvaval.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jrbnvaval.setText("Aval");
        jrbnvaval.setToolTipText("Aval");
        jrbnvaval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbnvavalActionPerformed(evt);
            }
        });

        bgnvestatus.add(jrbnvambos);
        jrbnvambos.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jrbnvambos.setText("Ambos");
        jrbnvambos.setToolTipText("Ambos");
        jrbnvambos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbnvambosActionPerformed(evt);
            }
        });

        jcbnvestatuscliente.setBackground(new java.awt.Color(167, 235, 242));
        jcbnvestatuscliente.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jcbnvestatuscliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estatus Cliente" }));
        jcbnvestatuscliente.setToolTipText("Selecciona un Estatus Cliente");
        jcbnvestatuscliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jcbnvestatuscliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcbnvestatuscliente.setEnabled(false);
        jcbnvestatuscliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbnvestatusclienteActionPerformed(evt);
            }
        });

        jcbnvestatusaval.setBackground(new java.awt.Color(167, 235, 242));
        jcbnvestatusaval.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jcbnvestatusaval.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estatus Aval" }));
        jcbnvestatusaval.setToolTipText("Selecciona un Estatus Aval");
        jcbnvestatusaval.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jcbnvestatusaval.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcbnvestatusaval.setEnabled(false);
        jcbnvestatusaval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbnvestatusavalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpfondonuevoclienteLayout = new javax.swing.GroupLayout(jpfondonuevocliente);
        jpfondonuevocliente.setLayout(jpfondonuevoclienteLayout);
        jpfondonuevoclienteLayout.setHorizontalGroup(
            jpfondonuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpfondonuevoclienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpfondonuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jcbnvzona, 0, 248, Short.MAX_VALUE)
                    .addComponent(jtfnvnombres, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfnvam, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfnvap, javax.swing.GroupLayout.Alignment.LEADING))
                .addGroup(jpfondonuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpfondonuevoclienteLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jpfondonuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbnvcliente)
                            .addComponent(jrbnvaval)
                            .addComponent(jrbnvambos))
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpfondonuevoclienteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpfondonuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbnvestatusaval, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbnvestatuscliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jpfondonuevoclienteLayout.setVerticalGroup(
            jpfondonuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpfondonuevoclienteLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jpfondonuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpfondonuevoclienteLayout.createSequentialGroup()
                        .addComponent(jrbnvcliente)
                        .addGap(18, 18, 18)
                        .addComponent(jrbnvaval))
                    .addGroup(jpfondonuevoclienteLayout.createSequentialGroup()
                        .addComponent(jtfnvnombres, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jpfondonuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfnvap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrbnvambos))
                .addGap(10, 10, 10)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jpfondonuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpfondonuevoclienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jcbnvestatusaval, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(jpfondonuevoclienteLayout.createSequentialGroup()
                        .addGroup(jpfondonuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfnvam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbnvestatuscliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jcbnvzona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))))
        );

        jLblIcono1.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLblIcono1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cliente_logo.png"))); // NOI18N

        jbcontinuar.setBackground(new java.awt.Color(204, 204, 204));
        jbcontinuar.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jbcontinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/continuar1.png"))); // NOI18N
        jbcontinuar.setText("Continuar");
        jbcontinuar.setBorder(null);
        jbcontinuar.setContentAreaFilled(false);
        jbcontinuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbcontinuar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbcontinuar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/continuar1.png"))); // NOI18N
        jbcontinuar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/continuar2.png"))); // NOI18N
        jbcontinuar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbcontinuar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbcontinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcontinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnuevoclienteLayout = new javax.swing.GroupLayout(jpnuevocliente);
        jpnuevocliente.setLayout(jpnuevoclienteLayout);
        jpnuevoclienteLayout.setHorizontalGroup(
            jpnuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnuevoclienteLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jpfondonuevocliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jpnuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnuevoclienteLayout.createSequentialGroup()
                        .addComponent(jLblIcono1)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnuevoclienteLayout.createSequentialGroup()
                        .addComponent(jbcontinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))))
        );
        jpnuevoclienteLayout.setVerticalGroup(
            jpnuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnuevoclienteLayout.createSequentialGroup()
                .addGroup(jpnuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnuevoclienteLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLblIcono1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbcontinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnuevoclienteLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jpfondonuevocliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jtppaneles.addTab("Agrega un Cliente", jpnuevocliente);

        jplistaclientes2.setBackground(new java.awt.Color(242, 220, 153));
        jplistaclientes2.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N

        jpfondotablaactyeli.setBackground(new java.awt.Color(242, 220, 153));

        jtlistaclienteavalactyeli.setBackground(new java.awt.Color(167, 235, 242));
        jtlistaclienteavalactyeli.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jtlistaclienteavalactyeli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador", "Nombre(s)", "Apellido Paterno", "Apellido Materno", "Estatus"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtlistaclienteavalactyeli.setToolTipText("Listado de Clientes y Avales");
        jtlistaclienteavalactyeli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jspclienteavalactyeli.setViewportView(jtlistaclienteavalactyeli);

        javax.swing.GroupLayout jpfondotablaactyeliLayout = new javax.swing.GroupLayout(jpfondotablaactyeli);
        jpfondotablaactyeli.setLayout(jpfondotablaactyeliLayout);
        jpfondotablaactyeliLayout.setHorizontalGroup(
            jpfondotablaactyeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpfondotablaactyeliLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspclienteavalactyeli, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpfondotablaactyeliLayout.setVerticalGroup(
            jpfondotablaactyeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpfondotablaactyeliLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspclienteavalactyeli, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jplistaclientes2Layout = new javax.swing.GroupLayout(jplistaclientes2);
        jplistaclientes2.setLayout(jplistaclientes2Layout);
        jplistaclientes2Layout.setHorizontalGroup(
            jplistaclientes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplistaclientes2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpfondotablaactyeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(330, Short.MAX_VALUE))
        );
        jplistaclientes2Layout.setVerticalGroup(
            jplistaclientes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplistaclientes2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpfondotablaactyeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtppaneles.addTab("Actualiza", jplistaclientes2);

        jplistaclientes3.setBackground(new java.awt.Color(242, 220, 153));
        jplistaclientes3.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N

        javax.swing.GroupLayout jplistaclientes3Layout = new javax.swing.GroupLayout(jplistaclientes3);
        jplistaclientes3.setLayout(jplistaclientes3Layout);
        jplistaclientes3Layout.setHorizontalGroup(
            jplistaclientes3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 851, Short.MAX_VALUE)
        );
        jplistaclientes3Layout.setVerticalGroup(
            jplistaclientes3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        jtppaneles.addTab("Lista Clientes", jplistaclientes3);

        javax.swing.GroupLayout jpfondoLayout = new javax.swing.GroupLayout(jpfondo);
        jpfondo.setLayout(jpfondoLayout);
        jpfondoLayout.setHorizontalGroup(
            jpfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtppaneles)
            .addGroup(jpfondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblIcono)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpfondoLayout.setVerticalGroup(
            jpfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpfondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 76, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtppaneles, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpfondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpfondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbnvclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbnvclienteActionPerformed
        jcbnvestatuscliente.setEnabled(true);
        jcbnvestatusaval.setEnabled(false);
    }//GEN-LAST:event_jrbnvclienteActionPerformed

    private void jrbnvavalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbnvavalActionPerformed
        jcbnvestatuscliente.setEnabled(false);
        jcbnvestatusaval.setEnabled(true);
    }//GEN-LAST:event_jrbnvavalActionPerformed

    private void jrbnvambosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbnvambosActionPerformed
        jcbnvestatuscliente.setEnabled(true);
        jcbnvestatusaval.setEnabled(true);
    }//GEN-LAST:event_jrbnvambosActionPerformed

    private void jcbnvzonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbnvzonaActionPerformed
        JComboBox jcb = (JComboBox) evt.getSource(); // Asegura que el evento venga del combo correcto
        seleccion = (String) jcb.getSelectedItem();
        if (!"Zona".equals(seleccion)) {
            z = seleccion;
            System.out.println(z);
            try {
                idZona = cb.buscarIdZona(z);
                System.out.println("ZONA " + idZona);
            } catch (SQLException ex) {
                Logger.getLogger(jfcliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jcbnvzonaActionPerformed

    private void jcbnvestatusclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbnvestatusclienteActionPerformed
        JComboBox jcb = (JComboBox) evt.getSource(); // Asegura que el evento venga del combo correcto
        seleccion = (String) jcb.getSelectedItem();
        if (!"Estatus".equals(seleccion)) {
            est = seleccion;
            System.out.println(est);
            try {
                idEstatus = cb.buscarIdEstatus(est);
                System.out.println("ESTATUS " + idEstatus);
            } catch (SQLException ex) {
                Logger.getLogger(jfcliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jcbnvestatusclienteActionPerformed

    private void jcbnvestatusavalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbnvestatusavalActionPerformed
        JComboBox jcb = (JComboBox) evt.getSource(); // Asegura que el evento venga del combo correcto
        seleccion = (String) jcb.getSelectedItem();
        if (!"Estatus".equals(seleccion)) {
            est = seleccion;
            System.out.println(est);
            try {
                idEstatusAval = cb.buscarIdEstatus(est);
                System.out.println("ESTATUS AVAL " + idEstatusAval);
            } catch (SQLException ex) {
                Logger.getLogger(jfcliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jcbnvestatusavalActionPerformed

    private void jbcontinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcontinuarActionPerformed
        String[] datosZona = new String[1];
        String[] datosPersona = new String[3];
        String[] datosEstatus = new String[2];

        JTextField[] jtf = {jtfnvnombres, jtfnvap, jtfnvam};
        String[] textosPredeterminados = {"Nombre(s)", "Apellido Paterno", "Apellido Materno"};
        String regexTexto = "^[A-Za-zÁÉÍÓÚáéíóúÑñ\\s]+$";

        try {
            // 1. Validar campos de texto
            boolean camposValidos = CUtilitarios.validaCamposTextoConFormato(
                    jtf, textosPredeterminados, textosPredeterminados, regexTexto,
                    "Debes llenar todos los campos correctamente", "Validación de Datos Persona"
            );
            if (!camposValidos) {
                return;
            }

            // 2. Validar zona seleccionada
            if (jcbnvzona.getSelectedIndex() == 0) {
                CUtilitarios.msg_advertencia("Selecciona una zona válida", "Validación de Zona");
                return;
            }

            // 3. Validar selección de tipo (cliente/aval/ambos)
            if (!jrbnvcliente.isSelected() && !jrbnvaval.isSelected() && !jrbnvambos.isSelected()) {
                CUtilitarios.msg_advertencia("Debes seleccionar Cliente, Aval o Ambos", "Validación de Opción");
                return;
            }

            // 4. Validar estatus según selección
            if (jrbnvcliente.isSelected()) {
                if (jcbnvestatuscliente.getSelectedIndex() == 0) {
                    CUtilitarios.msg_advertencia("Selecciona un estatus válido para cliente", "Validación de Estatus");
                    return;
                }
                datosEstatus[0] = idEstatus;

            } else if (jrbnvaval.isSelected()) {
                if (jcbnvestatusaval.getSelectedIndex() == 0) {
                    CUtilitarios.msg_advertencia("Selecciona un estatus válido para aval", "Validación de Estatus Aval");
                    return;
                }
                datosEstatus[1] = idEstatusAval;

            } else if (jrbnvambos.isSelected()) {
                if (jcbnvestatuscliente.getSelectedIndex() == 0 || jcbnvestatusaval.getSelectedIndex() == 0) {
                    CUtilitarios.msg_advertencia("Selecciona estatus válidos para Cliente y Aval", "Validación de Estatus");
                    return;
                }
                datosEstatus[0] = idEstatus;
                datosEstatus[1] = idEstatusAval;
            }

            // Preparar datos persona y zona
            datosPersona[0] = jtfnvnombres.getText().trim();
            datosPersona[1] = jtfnvap.getText().trim();
            datosPersona[2] = jtfnvam.getText().trim();
            datosZona[0] = idZona;

            // Si todo está validado, abrir la ventana de dirección
            jfdireccion dir = new jfdireccion(datosZona, datosPersona, datosEstatus);
            dir.setVisible(true);
            this.dispose();

        } catch (Exception e) {
            CUtilitarios.msg_error("Error inesperado", e.getMessage());
        }
    }//GEN-LAST:event_jbcontinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new jfcliente().setVisible(true);

                } catch (SQLException ex) {
                    Logger.getLogger(jfcliente.class
                            .getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgnvestatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblIcono;
    private javax.swing.JLabel jLblIcono1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JButton jbcontinuar;
    private javax.swing.JComboBox<String> jcbestatusbusqueda;
    private javax.swing.JComboBox<String> jcbnvestatusaval;
    private javax.swing.JComboBox<String> jcbnvestatuscliente;
    private javax.swing.JComboBox<String> jcbnvzona;
    private javax.swing.JComboBox<String> jcbusuariobusqueda;
    private javax.swing.JPanel jpfondo;
    private javax.swing.JPanel jpfondobusqueda;
    private javax.swing.JPanel jpfondonuevocliente;
    private javax.swing.JPanel jpfondotabla;
    private javax.swing.JPanel jpfondotablaactyeli;
    private javax.swing.JPanel jplistaclientes;
    private javax.swing.JPanel jplistaclientes2;
    private javax.swing.JPanel jplistaclientes3;
    private javax.swing.JPanel jpnuevocliente;
    private javax.swing.JRadioButton jrbnvambos;
    private javax.swing.JRadioButton jrbnvaval;
    private javax.swing.JRadioButton jrbnvcliente;
    private javax.swing.JScrollPane jspclienteaval;
    private javax.swing.JScrollPane jspclienteavalactyeli;
    private javax.swing.JTextField jtfambusqueda;
    private javax.swing.JTextField jtfapbusqueda;
    private javax.swing.JTextField jtfidbusqueda;
    private javax.swing.JTextField jtfnombresbusqueda;
    private javax.swing.JTextField jtfnvam;
    private javax.swing.JTextField jtfnvap;
    private javax.swing.JTextField jtfnvnombres;
    private javax.swing.JTable jtlistaclienteaval;
    private javax.swing.JTable jtlistaclienteavalactyeli;
    private javax.swing.JTabbedPane jtppaneles;
    // End of variables declaration//GEN-END:variables
}
