package Views.cliente;

import Views.direccion.*;
import crud.*;
import utilitarios.*;
import java.sql.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author micky
 */
public final class jfmenucliente extends javax.swing.JFrame {

    /**
     * Creates new form jfmenucliente
     */
    CUtilitarios cu = new CUtilitarios();
    CBusquedas cb = new CBusquedas();
    String seleccion, est, z, idZona, idEstatus, idEstatusAval;

    public jfmenucliente() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        cargaComboBox(jcbestatus, 1);
        cargaComboBox(jcbestatusn, 1);
        cargaComboBox(jcbestatusact, 1);
        cargaComboBox(jcbestatuseli, 1);
        cargaComboBox(jcbestatusavaln, 2);
        cargaComboBox(jcbestatusavalact, 2);
        cargaComboBox(jcbnzona, 3);
        cargaComboBox(jcbazona, 3);

        /* Placeholder JTField */
        cu.aplicarPlaceholder(jtfid, "Ingresa el ID de búsqueda");
        cu.aplicarPlaceholder(jtfnombres, "Ingresar nombre(s) de búsqueda");
        cu.aplicarPlaceholder(jtfappaterno, "Ingresar apellido paterno de búsqueda");
        cu.aplicarPlaceholder(jtfapmaterno, "Ingresar apellido materno de búsqueda");
        cu.aplicarPlaceholder(jtfnnombres, "Nombres");
        cu.aplicarPlaceholder(jtfnapppaterno, "Apellido Paterno");
        cu.aplicarPlaceholder(jtfnapmaterno, "Apellido Materno");
        cu.aplicarPlaceholder(jtfanombres, "Nombre (s)");
        cu.aplicarPlaceholder(jtfaapppaterno, "Apellido Paterno");
        cu.aplicarPlaceholder(jtfaapmaterno, "Apellido Materno");
        cu.aplicarPlaceholder(jtfideli, "Ingresa el ID de búsqueda");
        cu.aplicarPlaceholder(jtfnombreseli, "Ingresar nombre(s) de búsqueda");
        cu.aplicarPlaceholder(jtfappaternoeli, "Ingresar apellido paterno de búsqueda");
        cu.aplicarPlaceholder(jtfapmaternoeli, "Ingresar apellido materno de búsqueda");

        // Tablas
//        cu.cargarTabla(jtlistaclientes);
//        cu.cargarTabla(jtlistaclienteseli);
    }

    private DefaultComboBoxModel listas;
    private ArrayList<String> datosListas = new ArrayList<>();
    private final CCargaCombos queryCarga = new CCargaCombos();

    public void cargaComboBox(JComboBox combo, int metodoCarga) {
        listas = (DefaultComboBoxModel) combo.getModel();
        try {
            switch (metodoCarga) {
                case 1:
                    datosListas = queryCarga.cargaComboEstatus();
                    for (int i = 0; i < datosListas.size(); i++) {
                        listas.addElement(datosListas.get(i));
                    }
                    datosListas.clear();
                    break;
                case 2:
                    datosListas = queryCarga.cargaComboEstatusAval();
                    for (int i = 0; i < datosListas.size(); i++) {
                        listas.addElement(datosListas.get(i));
                    }
                    datosListas.clear();
                    break;
                case 3:
                    datosListas = queryCarga.cargaComboZona();
                    for (int i = 0; i < datosListas.size(); i++) {
                        listas.addElement(datosListas.get(i));
                    }
                    datosListas.clear();
                    break;
            }
        } catch (SQLException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        bgins = new javax.swing.ButtonGroup();
        bgact = new javax.swing.ButtonGroup();
        jpprincipal = new javax.swing.JPanel();
        jPnlLogZonas = new javax.swing.JPanel();
        jLblIcono = new javax.swing.JLabel();
        jtpprincipal = new javax.swing.JTabbedPane();
        jplistacliente = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtlistaclientes = new javax.swing.JTable();
        jtfid = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jtfnombres = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jtfappaterno = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jtfapmaterno = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jcbestatus = new javax.swing.JComboBox<>();
        jcbtipousuario = new javax.swing.JComboBox<>();
        jpnuevocliente = new javax.swing.JPanel();
        jtfnnombres = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jtfnapppaterno = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jtfnapmaterno = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jcbnzona = new javax.swing.JComboBox<>();
        jbagregar = new javax.swing.JButton();
        JlblImagen1 = new javax.swing.JLabel();
        jrbcliente = new javax.swing.JRadioButton();
        jrbaval = new javax.swing.JRadioButton();
        jrbambos = new javax.swing.JRadioButton();
        jcbestatusn = new javax.swing.JComboBox<>();
        jcbestatusavaln = new javax.swing.JComboBox<>();
        jpactualizacliente = new javax.swing.JPanel();
        jpnuevocliente1 = new javax.swing.JPanel();
        JlblImagen = new javax.swing.JLabel();
        jtfanombres = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jtfaapppaterno = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jtfaapmaterno = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jcbazona = new javax.swing.JComboBox<>();
        jbactualizar = new javax.swing.JButton();
        jrbclienteact = new javax.swing.JRadioButton();
        jrbavalact = new javax.swing.JRadioButton();
        jrbambosact = new javax.swing.JRadioButton();
        jcbestatusact = new javax.swing.JComboBox<>();
        jcbestatusavalact = new javax.swing.JComboBox<>();
        jpeliminacliente = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtlistaclienteseli = new javax.swing.JTable();
        jtfideli = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jtfnombreseli = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jtfappaternoeli = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jtfapmaternoeli = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jcbestatuseli = new javax.swing.JComboBox<>();
        jcbtipousuarioeli = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpprincipal.setBackground(new java.awt.Color(242, 220, 153));

        jPnlLogZonas.setBackground(new java.awt.Color(242, 220, 153));

        jLblIcono.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cliente.png"))); // NOI18N
        jLblIcono.setText("  Clientes");

        javax.swing.GroupLayout jPnlLogZonasLayout = new javax.swing.GroupLayout(jPnlLogZonas);
        jPnlLogZonas.setLayout(jPnlLogZonasLayout);
        jPnlLogZonasLayout.setHorizontalGroup(
            jPnlLogZonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlLogZonasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblIcono)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnlLogZonasLayout.setVerticalGroup(
            jPnlLogZonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlLogZonasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblIcono)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtpprincipal.setBackground(new java.awt.Color(242, 220, 153));
        jtpprincipal.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N

        jplistacliente.setBackground(new java.awt.Color(242, 220, 153));

        jtlistaclientes.setBackground(new java.awt.Color(167, 235, 242));
        jtlistaclientes.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jtlistaclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Cliente", "Nombre (s)", "Apellido Paterno", "Apellido Materno", "Estatus"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtlistaclientes);
        if (jtlistaclientes.getColumnModel().getColumnCount() > 0) {
            jtlistaclientes.getColumnModel().getColumn(4).setHeaderValue("Estatus");
        }

        jtfid.setBackground(new java.awt.Color(242, 220, 153));
        jtfid.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jtfid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfid.setText("Ingresa el ID de búsqueda");
        jtfid.setToolTipText("");
        jtfid.setBorder(null);
        jtfid.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setToolTipText("");

        jtfnombres.setBackground(new java.awt.Color(242, 220, 153));
        jtfnombres.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jtfnombres.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfnombres.setText("Ingresar nombre(s) de búsqueda");
        jtfnombres.setToolTipText("");
        jtfnombres.setBorder(null);
        jtfnombres.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setToolTipText("");

        jtfappaterno.setBackground(new java.awt.Color(242, 220, 153));
        jtfappaterno.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jtfappaterno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfappaterno.setText("Ingresar apellido paterno de búsqueda");
        jtfappaterno.setToolTipText("Ingresar apellido paterno de búsqueda");
        jtfappaterno.setBorder(null);
        jtfappaterno.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setToolTipText("");

        jtfapmaterno.setBackground(new java.awt.Color(242, 220, 153));
        jtfapmaterno.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jtfapmaterno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfapmaterno.setText("Ingresar apellido materno de búsqueda");
        jtfapmaterno.setToolTipText("");
        jtfapmaterno.setBorder(null);
        jtfapmaterno.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setToolTipText("");

        jcbestatus.setBackground(new java.awt.Color(242, 220, 153));
        jcbestatus.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jcbestatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estatus" }));
        jcbestatus.setToolTipText("");
        jcbestatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jcbtipousuario.setBackground(new java.awt.Color(242, 220, 153));
        jcbtipousuario.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jcbtipousuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo Usuario" }));
        jcbtipousuario.setToolTipText("");
        jcbtipousuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jplistaclienteLayout = new javax.swing.GroupLayout(jplistacliente);
        jplistacliente.setLayout(jplistaclienteLayout);
        jplistaclienteLayout.setHorizontalGroup(
            jplistaclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplistaclienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jplistaclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcbestatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfappaterno)
                    .addComponent(jtfnombres)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4)
                    .addComponent(jtfid)
                    .addComponent(jtfapmaterno)
                    .addComponent(jcbtipousuario, 0, 270, Short.MAX_VALUE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jplistaclienteLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jcbestatus, jcbtipousuario});

        jplistaclienteLayout.setVerticalGroup(
            jplistaclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplistaclienteLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jplistaclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jplistaclienteLayout.createSequentialGroup()
                        .addComponent(jtfid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jtfnombres, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jtfappaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jtfapmaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jcbestatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcbtipousuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jplistaclienteLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jcbestatus, jcbtipousuario});

        jtpprincipal.addTab("Lista Clientes", jplistacliente);

        jpnuevocliente.setBackground(new java.awt.Color(242, 220, 153));

        jtfnnombres.setBackground(new java.awt.Color(242, 220, 153));
        jtfnnombres.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jtfnnombres.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtfnnombres.setText("Nombres");
        jtfnnombres.setToolTipText("");
        jtfnnombres.setBorder(null);
        jtfnnombres.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator5.setToolTipText("");

        jtfnapppaterno.setBackground(new java.awt.Color(242, 220, 153));
        jtfnapppaterno.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jtfnapppaterno.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtfnapppaterno.setText("Apellido Paterno");
        jtfnapppaterno.setToolTipText("");
        jtfnapppaterno.setBorder(null);
        jtfnapppaterno.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator6.setToolTipText("");

        jtfnapmaterno.setBackground(new java.awt.Color(242, 220, 153));
        jtfnapmaterno.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jtfnapmaterno.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtfnapmaterno.setText("Apellido Materno");
        jtfnapmaterno.setToolTipText("");
        jtfnapmaterno.setBorder(null);
        jtfnapmaterno.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator7.setToolTipText("");

        jcbnzona.setBackground(new java.awt.Color(242, 220, 153));
        jcbnzona.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jcbnzona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Zona" }));
        jcbnzona.setToolTipText("");
        jcbnzona.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jcbnzona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbnzonaActionPerformed(evt);
            }
        });

        jbagregar.setBackground(new java.awt.Color(56, 171, 242));
        jbagregar.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jbagregar.setText("Agregar");
        jbagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbagregarActionPerformed(evt);
            }
        });

        JlblImagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_vectori.png"))); // NOI18N

        bgins.add(jrbcliente);
        jrbcliente.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jrbcliente.setText("Cliente");
        jrbcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbclienteActionPerformed(evt);
            }
        });

        bgins.add(jrbaval);
        jrbaval.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jrbaval.setText("Aval");
        jrbaval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbavalActionPerformed(evt);
            }
        });

        bgins.add(jrbambos);
        jrbambos.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jrbambos.setText("Ambos");
        jrbambos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbambosActionPerformed(evt);
            }
        });

        jcbestatusn.setBackground(new java.awt.Color(242, 220, 153));
        jcbestatusn.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jcbestatusn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estatus" }));
        jcbestatusn.setToolTipText("");
        jcbestatusn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jcbestatusn.setEnabled(false);
        jcbestatusn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbestatusnActionPerformed(evt);
            }
        });

        jcbestatusavaln.setBackground(new java.awt.Color(242, 220, 153));
        jcbestatusavaln.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jcbestatusavaln.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estatus Aval" }));
        jcbestatusavaln.setToolTipText("");
        jcbestatusavaln.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jcbestatusavaln.setEnabled(false);
        jcbestatusavaln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbestatusavalnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnuevoclienteLayout = new javax.swing.GroupLayout(jpnuevocliente);
        jpnuevocliente.setLayout(jpnuevoclienteLayout);
        jpnuevoclienteLayout.setHorizontalGroup(
            jpnuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnuevoclienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                        .addComponent(jtfnapmaterno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                        .addComponent(jtfnapppaterno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                        .addComponent(jtfnnombres, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                    .addComponent(jcbnzona, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(118, 118, 118)
                .addGroup(jpnuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbestatusavaln, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrbaval)
                    .addComponent(jrbambos)
                    .addComponent(jrbcliente)
                    .addComponent(jcbestatusn, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(JlblImagen1)
                .addGap(17, 17, 17))
            .addGroup(jpnuevoclienteLayout.createSequentialGroup()
                .addGap(432, 432, 432)
                .addComponent(jbagregar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnuevoclienteLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jSeparator5, jtfnnombres});

        jpnuevoclienteLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jSeparator6, jtfnapppaterno});

        jpnuevoclienteLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jSeparator7, jtfnapmaterno});

        jpnuevoclienteLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jrbambos, jrbaval, jrbcliente});

        jpnuevoclienteLayout.setVerticalGroup(
            jpnuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnuevoclienteLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jpnuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnuevoclienteLayout.createSequentialGroup()
                        .addComponent(jtfnnombres, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpnuevoclienteLayout.createSequentialGroup()
                                .addGroup(jpnuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpnuevoclienteLayout.createSequentialGroup()
                                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(jtfnapppaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)
                                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpnuevoclienteLayout.createSequentialGroup()
                                        .addComponent(jrbcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrbaval, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrbambos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(24, 24, 24)
                                .addComponent(jtfnapmaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jcbestatusn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jpnuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbnzona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbestatusavaln, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnuevoclienteLayout.createSequentialGroup()
                        .addComponent(JlblImagen1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jbagregar)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jpnuevoclienteLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jrbambos, jrbaval, jrbcliente});

        jtpprincipal.addTab("Agregar Cliente", jpnuevocliente);

        jpactualizacliente.setBackground(new java.awt.Color(242, 220, 153));

        jpnuevocliente1.setBackground(new java.awt.Color(242, 220, 153));

        JlblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_vectori.png"))); // NOI18N

        jtfanombres.setBackground(new java.awt.Color(242, 220, 153));
        jtfanombres.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jtfanombres.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtfanombres.setText("Nombres");
        jtfanombres.setToolTipText("");
        jtfanombres.setBorder(null);
        jtfanombres.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jSeparator12.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator12.setToolTipText("");

        jtfaapppaterno.setBackground(new java.awt.Color(242, 220, 153));
        jtfaapppaterno.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jtfaapppaterno.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtfaapppaterno.setText("Apellido Paterno");
        jtfaapppaterno.setToolTipText("");
        jtfaapppaterno.setBorder(null);
        jtfaapppaterno.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jSeparator13.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator13.setToolTipText("");

        jtfaapmaterno.setBackground(new java.awt.Color(242, 220, 153));
        jtfaapmaterno.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jtfaapmaterno.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtfaapmaterno.setText("Apellido Materno");
        jtfaapmaterno.setToolTipText("");
        jtfaapmaterno.setBorder(null);
        jtfaapmaterno.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jSeparator14.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator14.setToolTipText("");

        jcbazona.setBackground(new java.awt.Color(242, 220, 153));
        jcbazona.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jcbazona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Zona" }));
        jcbazona.setToolTipText("");
        jcbazona.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jbactualizar.setBackground(new java.awt.Color(56, 171, 242));
        jbactualizar.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jbactualizar.setText("Actualizar");

        bgact.add(jrbclienteact);
        jrbclienteact.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jrbclienteact.setText("Cliente");

        bgact.add(jrbavalact);
        jrbavalact.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jrbavalact.setText("Aval");

        bgact.add(jrbambosact);
        jrbambosact.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jrbambosact.setText("Ambos");

        jcbestatusact.setBackground(new java.awt.Color(242, 220, 153));
        jcbestatusact.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jcbestatusact.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estatus" }));
        jcbestatusact.setToolTipText("");
        jcbestatusact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jcbestatusavalact.setBackground(new java.awt.Color(242, 220, 153));
        jcbestatusavalact.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jcbestatusavalact.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estatus Aval" }));
        jcbestatusavalact.setToolTipText("");
        jcbestatusavalact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jpnuevocliente1Layout = new javax.swing.GroupLayout(jpnuevocliente1);
        jpnuevocliente1.setLayout(jpnuevocliente1Layout);
        jpnuevocliente1Layout.setHorizontalGroup(
            jpnuevocliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnuevocliente1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(JlblImagen)
                .addGap(18, 18, 18)
                .addGroup(jpnuevocliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbazona, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfaapmaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfaapppaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfanombres, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(jpnuevocliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbestatusavalact, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbestatusact, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrbavalact)
                    .addComponent(jrbambosact)
                    .addComponent(jrbclienteact))
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnuevocliente1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbactualizar)
                .addGap(261, 261, 261))
        );
        jpnuevocliente1Layout.setVerticalGroup(
            jpnuevocliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnuevocliente1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbactualizar)
                .addGap(99, 99, 99))
            .addGroup(jpnuevocliente1Layout.createSequentialGroup()
                .addGroup(jpnuevocliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnuevocliente1Layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jcbazona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnuevocliente1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jpnuevocliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfanombres, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbestatusact, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnuevocliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnuevocliente1Layout.createSequentialGroup()
                                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addGroup(jpnuevocliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtfaapppaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbestatusavalact, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addGroup(jpnuevocliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpnuevocliente1Layout.createSequentialGroup()
                                        .addComponent(jtfaapmaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpnuevocliente1Layout.createSequentialGroup()
                                        .addComponent(jrbclienteact, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrbavalact, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrbambosact, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(JlblImagen))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpactualizaclienteLayout = new javax.swing.GroupLayout(jpactualizacliente);
        jpactualizacliente.setLayout(jpactualizaclienteLayout);
        jpactualizaclienteLayout.setHorizontalGroup(
            jpactualizaclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnuevocliente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpactualizaclienteLayout.setVerticalGroup(
            jpactualizaclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnuevocliente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jtpprincipal.addTab("Actualizar Cliente", jpactualizacliente);

        jpeliminacliente.setBackground(new java.awt.Color(242, 220, 153));

        jtlistaclienteseli.setBackground(new java.awt.Color(167, 235, 242));
        jtlistaclienteseli.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jtlistaclienteseli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Cliente", "Nombre (s)", "Apellido Paterno", "Apellido Materno"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtlistaclienteseli);

        jtfideli.setBackground(new java.awt.Color(242, 220, 153));
        jtfideli.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jtfideli.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfideli.setText("Ingresa el ID de búsqueda");
        jtfideli.setToolTipText("");
        jtfideli.setBorder(null);
        jtfideli.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator8.setToolTipText("");

        jtfnombreseli.setBackground(new java.awt.Color(242, 220, 153));
        jtfnombreseli.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jtfnombreseli.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfnombreseli.setText("Ingresar nombre(s) de búsqueda");
        jtfnombreseli.setToolTipText("");
        jtfnombreseli.setBorder(null);
        jtfnombreseli.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator9.setToolTipText("");

        jtfappaternoeli.setBackground(new java.awt.Color(242, 220, 153));
        jtfappaternoeli.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jtfappaternoeli.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfappaternoeli.setText("Ingresr apellido paterno de búsqueda");
        jtfappaternoeli.setToolTipText("");
        jtfappaternoeli.setBorder(null);
        jtfappaternoeli.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator10.setToolTipText("");

        jtfapmaternoeli.setBackground(new java.awt.Color(242, 220, 153));
        jtfapmaternoeli.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jtfapmaternoeli.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfapmaternoeli.setText("Ingresar apellido materno de búsqueda");
        jtfapmaternoeli.setToolTipText("");
        jtfapmaternoeli.setBorder(null);
        jtfapmaternoeli.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator11.setToolTipText("");

        jcbestatuseli.setBackground(new java.awt.Color(242, 220, 153));
        jcbestatuseli.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jcbestatuseli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estatus" }));
        jcbestatuseli.setToolTipText("");
        jcbestatuseli.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jcbtipousuarioeli.setBackground(new java.awt.Color(242, 220, 153));
        jcbtipousuarioeli.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jcbtipousuarioeli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo Usuario" }));
        jcbtipousuarioeli.setToolTipText("");
        jcbtipousuarioeli.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jpeliminaclienteLayout = new javax.swing.GroupLayout(jpeliminacliente);
        jpeliminacliente.setLayout(jpeliminaclienteLayout);
        jpeliminaclienteLayout.setHorizontalGroup(
            jpeliminaclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpeliminaclienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jpeliminaclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcbestatuseli, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfappaternoeli)
                    .addComponent(jtfnombreseli)
                    .addComponent(jSeparator8)
                    .addComponent(jSeparator9)
                    .addComponent(jSeparator10)
                    .addComponent(jSeparator11)
                    .addComponent(jtfideli)
                    .addComponent(jtfapmaternoeli)
                    .addComponent(jcbtipousuarioeli, 0, 270, Short.MAX_VALUE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jpeliminaclienteLayout.setVerticalGroup(
            jpeliminaclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpeliminaclienteLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jpeliminaclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpeliminaclienteLayout.createSequentialGroup()
                        .addComponent(jtfideli, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jtfnombreseli, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jtfappaternoeli, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jtfapmaternoeli, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jcbestatuseli, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcbtipousuarioeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jtpprincipal.addTab("Eliminar Cliente", jpeliminacliente);

        javax.swing.GroupLayout jpprincipalLayout = new javax.swing.GroupLayout(jpprincipal);
        jpprincipal.setLayout(jpprincipalLayout);
        jpprincipalLayout.setHorizontalGroup(
            jpprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlLogZonas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jtpprincipal)
        );
        jpprincipalLayout.setVerticalGroup(
            jpprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpprincipalLayout.createSequentialGroup()
                .addComponent(jPnlLogZonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtpprincipal))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpprincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbclienteActionPerformed
        jcbestatusn.setEnabled(true);
        jcbestatusavaln.setEnabled(false);
    }//GEN-LAST:event_jrbclienteActionPerformed

    private void jrbavalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbavalActionPerformed
        jcbestatusn.setEnabled(false);
        jcbestatusavaln.setEnabled(true);
    }//GEN-LAST:event_jrbavalActionPerformed

    private void jrbambosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbambosActionPerformed
        jcbestatusn.setEnabled(true);
        jcbestatusavaln.setEnabled(true);
    }//GEN-LAST:event_jrbambosActionPerformed

    private void jcbestatusnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbestatusnActionPerformed
        JComboBox jcb = (JComboBox) evt.getSource(); // Asegura que el evento venga del combo correcto
        seleccion = (String) jcb.getSelectedItem();
        if (!"Estatus".equals(seleccion)) {
            est = seleccion;
            System.out.println(est);
            try {
                idEstatus = cb.buscarIdEstatus(est);
                System.out.println("ESTATUS " + idEstatus);
            } catch (SQLException ex) {
                Logger.getLogger(jfmenucliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jcbestatusnActionPerformed

    private void jcbestatusavalnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbestatusavalnActionPerformed
        JComboBox jcb = (JComboBox) evt.getSource(); // Asegura que el evento venga del combo correcto
        seleccion = (String) jcb.getSelectedItem();
        if (!"Estatus".equals(seleccion)) {
            est = seleccion;
            System.out.println(est);
            try {
                idEstatusAval = cb.buscarIdEstatus(est);
                System.out.println("ESTATUS AVAL " + idEstatusAval);
            } catch (SQLException ex) {
                Logger.getLogger(jfmenucliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jcbestatusavalnActionPerformed

    private void jcbnzonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbnzonaActionPerformed
        JComboBox jcb = (JComboBox) evt.getSource(); // Asegura que el evento venga del combo correcto
        seleccion = (String) jcb.getSelectedItem();
        if (!"Zona".equals(seleccion)) {
            z = seleccion;
            System.out.println(z);
            try {
                idZona = cb.buscarIdZona(z);
                System.out.println("ZONA " + idZona);
            } catch (SQLException ex) {
                Logger.getLogger(jfmenucliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jcbnzonaActionPerformed

    private void jbagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbagregarActionPerformed
        String[] datosZona = new String[1];
        String[] datosPersona = new String[3];
        String[] datosEstatus = new String[2];

        JTextField[] jtf = {jtfnnombres, jtfnapppaterno, jtfnapmaterno};
        String[] textosPredeterminados = {"Nombres", "Apellido Paterno", "Apellido Materno"};
        String regexTexto = "^[A-Za-zÁÉÍÓÚáéíóúÑñ\\s]+$";

        try {
            // 1. Validar campos de texto
            boolean camposValidos = CUtilitarios.validaCamposTextoConFormato(
                    jtf, textosPredeterminados, textosPredeterminados, regexTexto,
                    "Debes llenar todos los campos correctamente", "Validación de Datos Persona"
            );
            if (!camposValidos) {
                return;
            }

            // 2. Validar zona seleccionada
            if (jcbnzona.getSelectedIndex() == 0) {
                CUtilitarios.msg_advertencia("Selecciona una zona válida", "Validación de Zona");
                return;
            }

            // 3. Validar selección de tipo (cliente/aval/ambos)
            if (!jrbcliente.isSelected() && !jrbaval.isSelected() && !jrbambos.isSelected()) {
                CUtilitarios.msg_advertencia("Debes seleccionar Cliente, Aval o Ambos", "Validación de Opción");
                return;
            }

            // 4. Validar estatus según selección
            if (jrbcliente.isSelected()) {
                if (jcbestatusn.getSelectedIndex() == 0) {
                    CUtilitarios.msg_advertencia("Selecciona un estatus válido para cliente", "Validación de Estatus");
                    return;
                }
                //datosEstatus[0] = String.valueOf(jcbestatusn.getSelectedIndex());
                datosEstatus[0] = idEstatus;

            } else if (jrbaval.isSelected()) {
                if (jcbestatusavaln.getSelectedIndex() == 0) {
                    CUtilitarios.msg_advertencia("Selecciona un estatus válido para aval", "Validación de Estatus Aval");
                    return;
                }
                //datosEstatus[1] = String.valueOf(jcbestatusavaln.getSelectedIndex());
                datosEstatus[1] = idEstatusAval;

            } else if (jrbambos.isSelected()) {
                if (jcbestatusn.getSelectedIndex() == 0 || jcbestatusavaln.getSelectedIndex() == 0) {
                    CUtilitarios.msg_advertencia("Selecciona estatus válidos para Cliente y Aval", "Validación de Estatus");
                    return;
                }
                //datosEstatus[0] = String.valueOf(jcbestatusn.getSelectedIndex());
                //datosEstatus[1] = String.valueOf(jcbestatusavaln.getSelectedIndex());
                datosEstatus[0] = idEstatus;
                datosEstatus[1] = idEstatusAval;
            }

            // Preparar datos persona y zona
            datosPersona[0] = jtfnnombres.getText().trim();
            datosPersona[1] = jtfnapppaterno.getText().trim();
            datosPersona[2] = jtfnapmaterno.getText().trim();
            datosZona[0] = idZona;

            // Si todo está validado, abrir la ventana de dirección
            jfnuevad dir = new jfnuevad(datosZona, datosPersona, datosEstatus);
            dir.setVisible(true);
            this.dispose();

        } catch (Exception e) {
            CUtilitarios.msg_error("Error inesperado", e.getMessage());
        }

    }//GEN-LAST:event_jbagregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfmenucliente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfmenucliente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfmenucliente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfmenucliente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new jfmenucliente().setVisible(true);

                } catch (SQLException ex) {
                    Logger.getLogger(jfmenucliente.class
                            .getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlblImagen;
    private javax.swing.JLabel JlblImagen1;
    private javax.swing.ButtonGroup bgact;
    private javax.swing.ButtonGroup bgins;
    private javax.swing.JLabel jLblIcono;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPnlLogZonas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JButton jbactualizar;
    private javax.swing.JButton jbagregar;
    private javax.swing.JComboBox<String> jcbazona;
    private javax.swing.JComboBox<String> jcbestatus;
    private javax.swing.JComboBox<String> jcbestatusact;
    private javax.swing.JComboBox<String> jcbestatusavalact;
    private javax.swing.JComboBox<String> jcbestatusavaln;
    private javax.swing.JComboBox<String> jcbestatuseli;
    private javax.swing.JComboBox<String> jcbestatusn;
    private javax.swing.JComboBox<String> jcbnzona;
    private javax.swing.JComboBox<String> jcbtipousuario;
    private javax.swing.JComboBox<String> jcbtipousuarioeli;
    private javax.swing.JPanel jpactualizacliente;
    private javax.swing.JPanel jpeliminacliente;
    private javax.swing.JPanel jplistacliente;
    private javax.swing.JPanel jpnuevocliente;
    private javax.swing.JPanel jpnuevocliente1;
    private javax.swing.JPanel jpprincipal;
    private javax.swing.JRadioButton jrbambos;
    private javax.swing.JRadioButton jrbambosact;
    private javax.swing.JRadioButton jrbaval;
    private javax.swing.JRadioButton jrbavalact;
    private javax.swing.JRadioButton jrbcliente;
    private javax.swing.JRadioButton jrbclienteact;
    private javax.swing.JTextField jtfaapmaterno;
    private javax.swing.JTextField jtfaapppaterno;
    private javax.swing.JTextField jtfanombres;
    private javax.swing.JTextField jtfapmaterno;
    private javax.swing.JTextField jtfapmaternoeli;
    private javax.swing.JTextField jtfappaterno;
    private javax.swing.JTextField jtfappaternoeli;
    private javax.swing.JTextField jtfid;
    private javax.swing.JTextField jtfideli;
    private javax.swing.JTextField jtfnapmaterno;
    private javax.swing.JTextField jtfnapppaterno;
    private javax.swing.JTextField jtfnnombres;
    private javax.swing.JTextField jtfnombres;
    private javax.swing.JTextField jtfnombreseli;
    private javax.swing.JTable jtlistaclientes;
    private javax.swing.JTable jtlistaclienteseli;
    private javax.swing.JTabbedPane jtpprincipal;
    // End of variables declaration//GEN-END:variables
}
