package Views;

import Views.cliente.jfcliente;
import Views.empleado.JfEmpleado;
import Views.productos.jfproductos;
import Views.venta.jfventa;
import Views.zonas.jfzonas;
import java.awt.Image;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import utilitarios.CUtilitarios;

/**
 *
 * @author micky
 */
public class jfmenuinicio extends javax.swing.JFrame {

    /**
     * Creates new form jfmenuinicio
     */
    public jfmenuinicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        agregaDiseño();
    }

    CUtilitarios cu = new CUtilitarios();
    private ImageIcon logo;
    private Icon icono;
    String[] datos = {};

    private void iconos(String ruta, JLabel jl) {
        this.logo = new ImageIcon(ruta);
        this.icono = new ImageIcon(this.logo.getImage().getScaledInstance(jl.getWidth(), jl.getHeight(), Image.SCALE_DEFAULT));
        jl.setIcon(this.icono);
        this.repaint();
    }

    private void agregaDiseño() {
        cu.estiloMenu(jmbmenu);
        cu.estiloMenu(jmalmacen, "/imagenes/almacen.png");
        cu.estiloMenu(jmcliente, "/imagenes/cliente.png");
        cu.estiloMenu(jmempleado, "/imagenes/iconoEmpleado.png");
        cu.estiloMenu(jmventas, "/imagenes/ventas.png");
        cu.estiloMenu(jmzonas, "/imagenes/zona.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JlblImagen = new javax.swing.JLabel();
        jmbmenu = new javax.swing.JMenuBar();
        jmalmacen = new javax.swing.JMenu();
        jmcliente = new javax.swing.JMenu();
        jmempleado = new javax.swing.JMenu();
        jmventas = new javax.swing.JMenu();
        jmzonas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(242, 220, 153));

        JlblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_vectori.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(JlblImagen)
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(JlblImagen)
                .addContainerGap())
        );

        jmalmacen.setText("Almacen");
        jmalmacen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmalmacenMouseClicked(evt);
            }
        });
        jmbmenu.add(jmalmacen);

        jmcliente.setText("Cliente");
        jmcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmclienteMouseClicked(evt);
            }
        });
        jmbmenu.add(jmcliente);

        jmempleado.setText("Empleado");
        jmempleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmempleadoMouseClicked(evt);
            }
        });
        jmbmenu.add(jmempleado);

        jmventas.setText("Ventas");
        jmventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmventasMouseClicked(evt);
            }
        });
        jmbmenu.add(jmventas);

        jmzonas.setText("Zonas");
        jmzonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmzonasMouseClicked(evt);
            }
        });
        jmbmenu.add(jmzonas);

        setJMenuBar(jmbmenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmalmacenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmalmacenMouseClicked
        jfproductos pro = new jfproductos(datos);
        pro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmalmacenMouseClicked

    private void jmclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmclienteMouseClicked
        try {
            jfcliente cliente = new jfcliente();
            cliente.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(jfmenuinicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jmclienteMouseClicked

    private void jmempleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmempleadoMouseClicked
        try {
            JfEmpleado empleado = new JfEmpleado();
            empleado.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(jfmenuinicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jmempleadoMouseClicked

    private void jmventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmventasMouseClicked
        jfventa venta = new jfventa(datos);
        venta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmventasMouseClicked

    private void jmzonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmzonasMouseClicked
        jfzonas zona = new jfzonas();
        zona.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmzonasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfmenuinicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfmenuinicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfmenuinicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfmenuinicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfmenuinicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlblImagen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jmalmacen;
    private javax.swing.JMenuBar jmbmenu;
    private javax.swing.JMenu jmcliente;
    private javax.swing.JMenu jmempleado;
    private javax.swing.JMenu jmventas;
    private javax.swing.JMenu jmzonas;
    // End of variables declaration//GEN-END:variables
}
