package Views.direccion;

import Views.cliente.jfcliente;
import crud.*;
import java.sql.*;
import java.util.*;
import java.util.logging.*;
import javax.swing.*;
import utilitarios.*;

/**
 *
 * @author micky
 */
public final class jfactdirec extends javax.swing.JFrame {

    /**
     * Creates new form jfnuevadirec
     */
    private static String[] datosPersona, datosEstatus, datosZona;
    CUtilitarios cu = new CUtilitarios();
    CBusquedas cb = new CBusquedas();
    CInserciones ci = new CInserciones();
    CActualizaciones cact = new CActualizaciones();
    String seleccion, colcl, idColcl;
    private String cllcl, ne, ni, nomcla, apcla, amcla, telcla, idPersona, referencia, telefonoPersona, iddr;
    private String[] datosDireccion;
    private int idc, idescl, idescla, z, idDireccion;

    public jfactdirec(String[] datosZ, String[] datosP, String[] datosEs) throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        // Datos extraidos
        datosZona = datosZ;
        datosPersona = datosP;
        datosEstatus = datosEs;

        // Muestra de datos transaccionados
        System.out.println("\n\nEn dirección");
        System.out.println("Zona " + Arrays.toString(datosZ));
        System.out.println("Persona " + Arrays.toString(datosP));
        System.out.println("Estatus " + Arrays.toString(datosEs));
        telefonoPersona = datosP[3]; // teléfono
        idDireccion = cb.buscarIdDireccionPorTelefono(telefonoPersona);
        System.out.println("ID DIRECCION: " + idDireccion);
        datosDireccion = cb.buscarDirecPorID(idDireccion);
        System.out.println("Dirección :" + Arrays.toString(datosDireccion));
        cargarDirec(datosDireccion);
    }

    public void cargarDirec(String[] datosDireccion) {

        if (datosDireccion == null || datosDireccion.length < 4) {
            return;
        }

        // Asignar a variables internas
        cllcl = datosDireccion[0];
        ni = datosDireccion[1];
        ne = datosDireccion[2];
        colcl = datosDireccion[4];
        System.out.println(colcl);
        referencia = datosDireccion.length > 4 ? datosDireccion[3] : "";

        // Mostrar en la interfaz
        jtfcallen.setText(cllcl);
        jtfnumintn.setText(ni);
        jtfnumextn.setText(ne);
        jcbcolonian.setSelectedItem(colcl);
        jtxtaReferencia1.setText(referencia);
    }

    private DefaultComboBoxModel listas;
    private final CCargaCombos queryCarga = new CCargaCombos();

    public void cargaComboBox(String idZona) {
        DefaultComboBoxModel colonias = (DefaultComboBoxModel) jcbcolonian.getModel();
        try {
            ArrayList<String> datosListas = queryCarga.cargaComboColoniasZona(Integer.parseInt(idZona));
            for (int i = 0; i < datosListas.size(); i++) {
                colonias.addElement(datosListas.get(i));
            }
            datosListas.clear();
        } catch (SQLException e) {
        }
    }

    public boolean validaColonia() {
        if (jcbcolonian.getSelectedIndex() == 0
                || jcbcolonian.getSelectedItem().equals("Colonias")) {
            CUtilitarios.msg_advertencia("¡Selecciona una colonia!", "Colonias");
            return false;
        } else {
            try {
                idc = Integer.parseInt(
                        cb.buscarIdColonia((String) jcbcolonian.getSelectedItem())
                );
                return true;
            } catch (SQLException ex) {
                return false;
            }
        }
    }

    private boolean validarReferencia() {
        // Obtenemos el texto y usamos trim() para eliminar espacios al inicio y final
        String ref = jtxtaReferencia1.getText().trim();

        // 1. Validar que no esté vacío
        if (ref.isEmpty()) {
            CUtilitarios.msg_advertencia("El campo de referencia no puede estar vacío.", "Validación de Campos");
            jtxtaReferencia1.requestFocus();
            return false;
        }

        // 2. Validar que no exceda los 100 caracteres
        if (ref.length() > 100) {
            CUtilitarios.msg_advertencia("La referencia es muy larga. Máximo 100 caracteres.\nCaracteres actuales: " + ref.length(), "Validación de Campos");
            jtxtaReferencia1.requestFocus();
            return false;
        }

        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpfondo = new javax.swing.JPanel();
        jliconodirec = new javax.swing.JLabel();
        JlblImagen1 = new javax.swing.JLabel();
        jbagregardirec = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jtfcallen = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jtfnumextn = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jtfnumintn = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jcbcolonian = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtaReferencia1 = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jpfondo.setBackground(new java.awt.Color(242, 220, 153));

        jliconodirec.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jliconodirec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/direcciones.png"))); // NOI18N
        jliconodirec.setText("Dirección");

        JlblImagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/direc.png"))); // NOI18N

        jbagregardirec.setBackground(new java.awt.Color(204, 204, 204));
        jbagregardirec.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jbagregardirec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/finalizar1.png"))); // NOI18N
        jbagregardirec.setText("Finalizar");
        jbagregardirec.setBorder(null);
        jbagregardirec.setContentAreaFilled(false);
        jbagregardirec.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbagregardirec.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbagregardirec.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/finalizar1.png"))); // NOI18N
        jbagregardirec.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/finalizar2.png"))); // NOI18N
        jbagregardirec.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbagregardirec.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbagregardirec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbagregardirecActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(167, 235, 242));

        jtfcallen.setBackground(new java.awt.Color(167, 235, 242));
        jtfcallen.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jtfcallen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfcallen.setToolTipText("");
        jtfcallen.setBorder(null);
        jtfcallen.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator8.setToolTipText("");

        jtfnumextn.setBackground(new java.awt.Color(167, 235, 242));
        jtfnumextn.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jtfnumextn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfnumextn.setToolTipText("");
        jtfnumextn.setBorder(null);
        jtfnumextn.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator9.setToolTipText("");

        jtfnumintn.setBackground(new java.awt.Color(167, 235, 242));
        jtfnumintn.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jtfnumintn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfnumintn.setToolTipText("");
        jtfnumintn.setBorder(null);
        jtfnumintn.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator10.setToolTipText("");

        jcbcolonian.setBackground(new java.awt.Color(167, 235, 242));
        jcbcolonian.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jcbcolonian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Colonias" }));
        jcbcolonian.setToolTipText("");
        jcbcolonian.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtxtaReferencia1.setBackground(new java.awt.Color(167, 235, 242));
        jtxtaReferencia1.setColumns(20);
        jtxtaReferencia1.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jtxtaReferencia1.setRows(5);
        jtxtaReferencia1.setToolTipText("Referencias");
        jScrollPane2.setViewportView(jtxtaReferencia1);

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Referencias");

        jLabel7.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Colonias");

        jLabel8.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Numero Interior");

        jLabel9.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Numero Interior");

        jLabel10.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Calle");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbcolonian, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfnumextn, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfnumintn, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator10, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfcallen, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfcallen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtfnumextn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfnumintn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbcolonian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jpfondoLayout = new javax.swing.GroupLayout(jpfondo);
        jpfondo.setLayout(jpfondoLayout);
        jpfondoLayout.setHorizontalGroup(
            jpfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpfondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpfondoLayout.createSequentialGroup()
                        .addComponent(jliconodirec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jpfondoLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jpfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpfondoLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(JlblImagen1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jpfondoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbagregardirec, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101))))))
        );
        jpfondoLayout.setVerticalGroup(
            jpfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpfondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jliconodirec)
                .addGap(18, 18, 18)
                .addGroup(jpfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpfondoLayout.createSequentialGroup()
                        .addComponent(JlblImagen1)
                        .addGap(30, 30, 30)
                        .addComponent(jbagregardirec, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 49, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpfondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpfondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbagregardirecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbagregardirecActionPerformed
        System.out.println("Botón AGREGAR DIRECCIÓN presionado");

        JTextField[] campos = {jtfcallen, jtfnumextn, jtfnumintn};
        String[] textosPredeterminados = {"Calle", "Número Interior", "Número Exterior"};
        String regexTexto = "^[0-9A-Za-zÁÉÍÓÚáéíóúÑñ\\s.,\\-]+$";

        boolean camposValidos = CUtilitarios.validaCamposTextoConFormato(
                campos,
                textosPredeterminados,
                textosPredeterminados,
                regexTexto,
                "Debes llenar todos los campos correctamente",
                "Validación Dirección"
        );

        if (!camposValidos) {
            System.out.println("Falla validación de campos");
            return;
        }

        if (!validarReferencia()) {
            System.out.println("Falla validación de referencia");
            return;
        }

        if (!validaColonia()) {
            System.out.println("Falla validación de colonia");
            return;
        }

        try {
            // Datos de dirección
            String calle = jtfcallen.getText().trim();
            String numInt = jtfnumintn.getText().trim();
            String numExt = jtfnumextn.getText().trim();
            String ref = jtxtaReferencia1.getText().trim();

            // Colonia
            String coloniaSeleccionada = jcbcolonian.getSelectedItem().toString();
            int idColonia = Integer.parseInt(cb.buscarIdColonia(coloniaSeleccionada));

            // IDs necesarios
            String idDireccionStr = String.valueOf(idDireccion);
            String idPersonaStr = String.valueOf(idPersona);

            System.out.println("Actualizando dirección ID: " + idDireccionStr);
            System.out.println("Colonia ID: " + idColonia);

            // Actualización
            cact.actualizarDireccionYPersonaCL(
                    idDireccionStr,
                    calle,
                    numExt,
                    numInt,
                    ref,
                    String.valueOf(idColonia),
                    idPersonaStr,
                    datosPersona[0],
                    datosPersona[1],
                    datosPersona[2],
                    datosPersona[3]
            );

            CUtilitarios.msg(
                    "Dirección actualizada correctamente",
                    "Actualización Exitosa"
            );

            jfcliente jfcl = new jfcliente();
            this.dispose();
            CUtilitarios.creaFrame(jfcl, "Actualización");

        } catch (SQLException ex) {
            Logger.getLogger(jfactdirec.class.getName())
                    .log(Level.SEVERE, null, ex);

            CUtilitarios.msg(
                    "Error al actualizar la dirección:\n" + ex.getMessage(),
                    "Error"
            );
        }
    }//GEN-LAST:event_jbagregardirecActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (idc != 0) {
            cargaComboBox(String.valueOf(idc));
        } else {
            cargaComboBox(datosZona[0]);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfactdirec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfactdirec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfactdirec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfactdirec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new jfactdirec(datosZona, datosPersona, datosEstatus).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(jfactdirec.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlblImagen1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JButton jbagregardirec;
    private javax.swing.JComboBox<String> jcbcolonian;
    private javax.swing.JLabel jliconodirec;
    private javax.swing.JPanel jpfondo;
    private javax.swing.JTextField jtfcallen;
    private javax.swing.JTextField jtfnumextn;
    private javax.swing.JTextField jtfnumintn;
    private javax.swing.JTextArea jtxtaReferencia1;
    // End of variables declaration//GEN-END:variables
}
