package Views.direccion;

import java.sql.*;
import javax.swing.*;
import utilitarios.CUtilitarios;

/**
 *
 * @author micky
 */
public class jfdirec extends javax.swing.JFrame {

    /**
     * Creates new form jfdirec
     */
    
    CUtilitarios cu = new CUtilitarios();
    public jfdirec() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        // Tablas
        cargarTablas();
    }
    
    private String sqlDirec;

    private void cargarTablas() {
        sqlDirec = "Call tablaDirec";

        try {
            cu.cargarConsultaEnTabla(sqlDirec, jtlistadirec);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al cargar tablas: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpfondodireccion = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jplistadirec = new javax.swing.JPanel();
        jpfondotabladirec = new javax.swing.JPanel();
        jspdirec = new javax.swing.JScrollPane();
        jtlistadirec = new javax.swing.JTable();
        jpfondobusqueda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfidbusqueda = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jtfpersonabusqueda = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jtfcpbusqueda = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jcbusuariobusqueda = new javax.swing.JComboBox<>();
        jpactualizadirec = new javax.swing.JPanel();
        jliconodirec = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpfondodireccion.setBackground(new java.awt.Color(242, 220, 153));

        jplistadirec.setBackground(new java.awt.Color(242, 220, 153));
        jplistadirec.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N

        jpfondotabladirec.setBackground(new java.awt.Color(242, 220, 153));

        jtlistadirec.setBackground(new java.awt.Color(167, 235, 242));
        jtlistadirec.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jtlistadirec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtlistadirec.setToolTipText("Listado de Clientes y Avales");
        jtlistadirec.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jspdirec.setViewportView(jtlistadirec);

        javax.swing.GroupLayout jpfondotabladirecLayout = new javax.swing.GroupLayout(jpfondotabladirec);
        jpfondotabladirec.setLayout(jpfondotabladirecLayout);
        jpfondotabladirecLayout.setHorizontalGroup(
            jpfondotabladirecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpfondotabladirecLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspdirec, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpfondotabladirecLayout.setVerticalGroup(
            jpfondotabladirecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpfondotabladirecLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspdirec, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpfondobusqueda.setBackground(new java.awt.Color(167, 235, 242));

        jLabel1.setBackground(new java.awt.Color(167, 235, 242));
        jLabel1.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Realiza Búsqueda");

        jtfidbusqueda.setBackground(new java.awt.Color(167, 235, 242));
        jtfidbusqueda.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jtfidbusqueda.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtfidbusqueda.setText("Ingresar ID");
        jtfidbusqueda.setToolTipText("Ingresar ID");
        jtfidbusqueda.setBorder(null);
        jtfidbusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setToolTipText("");

        jtfpersonabusqueda.setBackground(new java.awt.Color(167, 235, 242));
        jtfpersonabusqueda.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jtfpersonabusqueda.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtfpersonabusqueda.setText("Ingresar Nombre de la Persona");
        jtfpersonabusqueda.setToolTipText("Ingresar Nombre(s)");
        jtfpersonabusqueda.setBorder(null);
        jtfpersonabusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setToolTipText("");

        jtfcpbusqueda.setBackground(new java.awt.Color(167, 235, 242));
        jtfcpbusqueda.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jtfcpbusqueda.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtfcpbusqueda.setText("Código Postal");
        jtfcpbusqueda.setToolTipText("Ingresar Apellido Paterno");
        jtfcpbusqueda.setBorder(null);
        jtfcpbusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setToolTipText("");

        jcbusuariobusqueda.setBackground(new java.awt.Color(167, 235, 242));
        jcbusuariobusqueda.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jcbusuariobusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de Usuario", "Cliente", "Aval", "Ambos" }));
        jcbusuariobusqueda.setToolTipText("Selecciona un tipo de Usuario");
        jcbusuariobusqueda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jcbusuariobusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jpfondobusquedaLayout = new javax.swing.GroupLayout(jpfondobusqueda);
        jpfondobusqueda.setLayout(jpfondobusquedaLayout);
        jpfondobusquedaLayout.setHorizontalGroup(
            jpfondobusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpfondobusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpfondobusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jcbusuariobusqueda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpfondobusquedaLayout.createSequentialGroup()
                        .addGroup(jpfondobusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfpersonabusqueda)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator1)
                            .addComponent(jtfidbusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addComponent(jtfcpbusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpfondobusquedaLayout.setVerticalGroup(
            jpfondobusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpfondobusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jtfidbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtfpersonabusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtfcpbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jcbusuariobusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jplistadirecLayout = new javax.swing.GroupLayout(jplistadirec);
        jplistadirec.setLayout(jplistadirecLayout);
        jplistadirecLayout.setHorizontalGroup(
            jplistadirecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplistadirecLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpfondotabladirec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jpfondobusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jplistadirecLayout.setVerticalGroup(
            jplistadirecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplistadirecLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplistadirecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpfondotabladirec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jplistadirecLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jpfondobusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Lista de Direcciones", jplistadirec);

        jpactualizadirec.setBackground(new java.awt.Color(242, 220, 153));
        jpactualizadirec.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N

        javax.swing.GroupLayout jpactualizadirecLayout = new javax.swing.GroupLayout(jpactualizadirec);
        jpactualizadirec.setLayout(jpactualizadirecLayout);
        jpactualizadirecLayout.setHorizontalGroup(
            jpactualizadirecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jpactualizadirecLayout.setVerticalGroup(
            jpactualizadirecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Actualizar Dirección", jpactualizadirec);

        jliconodirec.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jliconodirec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/direcciones.png"))); // NOI18N
        jliconodirec.setText("Dirección");

        javax.swing.GroupLayout jpfondodireccionLayout = new javax.swing.GroupLayout(jpfondodireccion);
        jpfondodireccion.setLayout(jpfondodireccionLayout);
        jpfondodireccionLayout.setHorizontalGroup(
            jpfondodireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jpfondodireccionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jliconodirec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpfondodireccionLayout.setVerticalGroup(
            jpfondodireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpfondodireccionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jliconodirec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpfondodireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpfondodireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfdirec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfdirec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfdirec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfdirec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new jfdirec().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> jcbusuariobusqueda;
    private javax.swing.JLabel jliconodirec;
    private javax.swing.JPanel jpactualizadirec;
    private javax.swing.JPanel jpfondobusqueda;
    private javax.swing.JPanel jpfondodireccion;
    private javax.swing.JPanel jpfondotabladirec;
    private javax.swing.JPanel jplistadirec;
    private javax.swing.JScrollPane jspdirec;
    private javax.swing.JTextField jtfcpbusqueda;
    private javax.swing.JTextField jtfidbusqueda;
    private javax.swing.JTextField jtfpersonabusqueda;
    private javax.swing.JTable jtlistadirec;
    // End of variables declaration//GEN-END:variables
}
