/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.zonas;

/**
 *
 * @author ADMIN
 */
public class jfmenuzonas extends javax.swing.JPanel {

    /**
     * Creates new form jfmenuzonas
     */
    public jfmenuzonas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpnlLogoZona = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPnlListaZonas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblBuscarZonas = new javax.swing.JTable();
        jPnlBusquedaZona = new javax.swing.JPanel();
        jLblBusquedaZona = new javax.swing.JLabel();
        jLblBIDZona = new javax.swing.JLabel();
        jLblBNumZona = new javax.swing.JLabel();
        jTxtBIDZona = new javax.swing.JTextField();
        jTxtBNumZona = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPnlAgrZona = new javax.swing.JPanel();
        jPnlActZona = new javax.swing.JPanel();
        jPnlEliZona = new javax.swing.JPanel();

        JpnlLogoZona.setBackground(new java.awt.Color(242, 220, 153));

        jLabel1.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zona.png"))); // NOI18N
        jLabel1.setText("Zonas");

        javax.swing.GroupLayout JpnlLogoZonaLayout = new javax.swing.GroupLayout(JpnlLogoZona);
        JpnlLogoZona.setLayout(JpnlLogoZonaLayout);
        JpnlLogoZonaLayout.setHorizontalGroup(
            JpnlLogoZonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnlLogoZonaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JpnlLogoZonaLayout.setVerticalGroup(
            JpnlLogoZonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnlLogoZonaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane1.setBackground(new java.awt.Color(242, 220, 153));
        jTabbedPane1.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N

        jPnlListaZonas.setBackground(new java.awt.Color(242, 220, 153));

        jtblBuscarZonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID zona", "Num. de zona"
            }
        ));
        jScrollPane1.setViewportView(jtblBuscarZonas);

        jPnlBusquedaZona.setBackground(new java.awt.Color(167, 235, 242));

        jLblBusquedaZona.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLblBusquedaZona.setText("Realizar Busqueda");

        jLblBIDZona.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLblBIDZona.setText("Ingresar ID de la zona: ");

        jLblBNumZona.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLblBNumZona.setText("Ingresar numero de la zona: ");

        jTxtBIDZona.setBackground(new java.awt.Color(167, 235, 242));
        jTxtBIDZona.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jTxtBIDZona.setBorder(null);

        jTxtBNumZona.setBackground(new java.awt.Color(167, 235, 242));
        jTxtBNumZona.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jTxtBNumZona.setBorder(null);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPnlBusquedaZonaLayout = new javax.swing.GroupLayout(jPnlBusquedaZona);
        jPnlBusquedaZona.setLayout(jPnlBusquedaZonaLayout);
        jPnlBusquedaZonaLayout.setHorizontalGroup(
            jPnlBusquedaZonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBusquedaZonaLayout.createSequentialGroup()
                .addGroup(jPnlBusquedaZonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlBusquedaZonaLayout.createSequentialGroup()
                        .addGroup(jPnlBusquedaZonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnlBusquedaZonaLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLblBusquedaZona))
                            .addGroup(jPnlBusquedaZonaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTxtBIDZona, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPnlBusquedaZonaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPnlBusquedaZonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblBIDZona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLblBNumZona, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addGroup(jPnlBusquedaZonaLayout.createSequentialGroup()
                                .addGroup(jPnlBusquedaZonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtBNumZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPnlBusquedaZonaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPnlBusquedaZonaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jSeparator1, jSeparator2, jTxtBIDZona, jTxtBNumZona});

        jPnlBusquedaZonaLayout.setVerticalGroup(
            jPnlBusquedaZonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBusquedaZonaLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLblBusquedaZona)
                .addGap(18, 18, 18)
                .addComponent(jLblBIDZona)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtBIDZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLblBNumZona)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtBNumZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPnlListaZonasLayout = new javax.swing.GroupLayout(jPnlListaZonas);
        jPnlListaZonas.setLayout(jPnlListaZonasLayout);
        jPnlListaZonasLayout.setHorizontalGroup(
            jPnlListaZonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlListaZonasLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPnlBusquedaZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPnlListaZonasLayout.setVerticalGroup(
            jPnlListaZonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlListaZonasLayout.createSequentialGroup()
                .addGroup(jPnlListaZonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlListaZonasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlListaZonasLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPnlBusquedaZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lista de zonas", jPnlListaZonas);

        jPnlAgrZona.setBackground(new java.awt.Color(242, 220, 153));

        javax.swing.GroupLayout jPnlAgrZonaLayout = new javax.swing.GroupLayout(jPnlAgrZona);
        jPnlAgrZona.setLayout(jPnlAgrZonaLayout);
        jPnlAgrZonaLayout.setHorizontalGroup(
            jPnlAgrZonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );
        jPnlAgrZonaLayout.setVerticalGroup(
            jPnlAgrZonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 332, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Agregar zona", jPnlAgrZona);

        jPnlActZona.setBackground(new java.awt.Color(242, 220, 153));

        javax.swing.GroupLayout jPnlActZonaLayout = new javax.swing.GroupLayout(jPnlActZona);
        jPnlActZona.setLayout(jPnlActZonaLayout);
        jPnlActZonaLayout.setHorizontalGroup(
            jPnlActZonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );
        jPnlActZonaLayout.setVerticalGroup(
            jPnlActZonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 332, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Actualizar zona", jPnlActZona);

        javax.swing.GroupLayout jPnlEliZonaLayout = new javax.swing.GroupLayout(jPnlEliZona);
        jPnlEliZona.setLayout(jPnlEliZonaLayout);
        jPnlEliZonaLayout.setHorizontalGroup(
            jPnlEliZonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );
        jPnlEliZonaLayout.setVerticalGroup(
            jPnlEliZonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 332, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Eliminar zona", jPnlEliZona);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpnlLogoZona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JpnlLogoZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpnlLogoZona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblBIDZona;
    private javax.swing.JLabel jLblBNumZona;
    private javax.swing.JLabel jLblBusquedaZona;
    private javax.swing.JPanel jPnlActZona;
    private javax.swing.JPanel jPnlAgrZona;
    private javax.swing.JPanel jPnlBusquedaZona;
    private javax.swing.JPanel jPnlEliZona;
    private javax.swing.JPanel jPnlListaZonas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTxtBIDZona;
    private javax.swing.JTextField jTxtBNumZona;
    private javax.swing.JTable jtblBuscarZonas;
    // End of variables declaration//GEN-END:variables
}
