/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.productos;

/**
 *
 * @author ADMIN
 */
public class jfmenuproductos extends javax.swing.JPanel {

    /**
     * Creates new form jfmenuproductos
     */
    public jfmenuproductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTPproductos = new javax.swing.JTabbedPane();
        JpnlListProducto = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblProductos1 = new javax.swing.JTable();
        jPnlBusquedaProducto = new javax.swing.JPanel();
        jLblBusqueda = new javax.swing.JLabel();
        jLblIngresarIDProducto = new javax.swing.JLabel();
        jLblIngresarNombreproducto = new javax.swing.JLabel();
        jLblIngresarPrecioProducto = new javax.swing.JLabel();
        jTxtIDProducto = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        JpnlLogoProducto1 = new javax.swing.JPanel();
        jLblAlmacen = new javax.swing.JLabel();

        jTPproductos.setBackground(new java.awt.Color(242, 220, 153));
        jTPproductos.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N

        JpnlListProducto.setBackground(new java.awt.Color(242, 220, 153));

        jtblProductos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Producto", "Producto", "Precio", "Stock"
            }
        ));
        jScrollPane1.setViewportView(jtblProductos1);

        jPnlBusquedaProducto.setBackground(new java.awt.Color(167, 235, 242));

        jLblBusqueda.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLblBusqueda.setText("Realizar Busqueda");

        jLblIngresarIDProducto.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLblIngresarIDProducto.setText("Ingresar ID del producto:\n");

        jLblIngresarNombreproducto.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLblIngresarNombreproducto.setText("Ingresar nombre del producto: ");

        jLblIngresarPrecioProducto.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLblIngresarPrecioProducto.setText("Ingresar precio del producto: ");

        jTxtIDProducto.setBackground(new java.awt.Color(167, 235, 242));
        jTxtIDProducto.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jTxtIDProducto.setBorder(null);

        jTextField2.setBackground(new java.awt.Color(167, 235, 242));
        jTextField2.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jTextField2.setBorder(null);

        jTextField3.setBackground(new java.awt.Color(167, 235, 242));
        jTextField3.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jTextField3.setBorder(null);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPnlBusquedaProductoLayout = new javax.swing.GroupLayout(jPnlBusquedaProducto);
        jPnlBusquedaProducto.setLayout(jPnlBusquedaProductoLayout);
        jPnlBusquedaProductoLayout.setHorizontalGroup(
            jPnlBusquedaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBusquedaProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlBusquedaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlBusquedaProductoLayout.createSequentialGroup()
                        .addGroup(jPnlBusquedaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblIngresarPrecioProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLblIngresarNombreproducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLblIngresarIDProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPnlBusquedaProductoLayout.createSequentialGroup()
                                .addGroup(jPnlBusquedaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtIDProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlBusquedaProductoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPnlBusquedaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlBusquedaProductoLayout.createSequentialGroup()
                                .addComponent(jLblBusqueda)
                                .addGap(56, 56, 56))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlBusquedaProductoLayout.createSequentialGroup()
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );

        jPnlBusquedaProductoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jSeparator1, jTxtIDProducto});

        jPnlBusquedaProductoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jSeparator3, jTextField3});

        jPnlBusquedaProductoLayout.setVerticalGroup(
            jPnlBusquedaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBusquedaProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblBusqueda)
                .addGap(18, 18, 18)
                .addComponent(jLblIngresarIDProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtIDProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblIngresarNombreproducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLblIngresarPrecioProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jPnlBusquedaProductoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jSeparator1, jTxtIDProducto});

        jPnlBusquedaProductoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jSeparator2, jTextField2});

        javax.swing.GroupLayout JpnlListProductoLayout = new javax.swing.GroupLayout(JpnlListProducto);
        JpnlListProducto.setLayout(JpnlListProductoLayout);
        JpnlListProductoLayout.setHorizontalGroup(
            JpnlListProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnlListProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPnlBusquedaProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        JpnlListProductoLayout.setVerticalGroup(
            JpnlListProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnlListProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpnlListProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPnlBusquedaProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTPproductos.addTab("Lista de productos", JpnlListProducto);

        jPanel2.setBackground(new java.awt.Color(242, 220, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );

        jTPproductos.addTab("Agregar producto", jPanel2);

        jPanel3.setBackground(new java.awt.Color(242, 220, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );

        jTPproductos.addTab("Actualizar producto", jPanel3);

        jPanel4.setBackground(new java.awt.Color(242, 220, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );

        jTPproductos.addTab("Eliminar producto", jPanel4);

        JpnlLogoProducto1.setBackground(new java.awt.Color(242, 220, 153));

        jLblAlmacen.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLblAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/almacen.png"))); // NOI18N
        jLblAlmacen.setText("Almacen");

        javax.swing.GroupLayout JpnlLogoProducto1Layout = new javax.swing.GroupLayout(JpnlLogoProducto1);
        JpnlLogoProducto1.setLayout(JpnlLogoProducto1Layout);
        JpnlLogoProducto1Layout.setHorizontalGroup(
            JpnlLogoProducto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnlLogoProducto1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblAlmacen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JpnlLogoProducto1Layout.setVerticalGroup(
            JpnlLogoProducto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnlLogoProducto1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblAlmacen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTPproductos)
            .addComponent(JpnlLogoProducto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(JpnlLogoProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTPproductos, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpnlListProducto;
    private javax.swing.JPanel JpnlLogoProducto1;
    private javax.swing.JLabel jLblAlmacen;
    private javax.swing.JLabel jLblBusqueda;
    private javax.swing.JLabel jLblIngresarIDProducto;
    private javax.swing.JLabel jLblIngresarNombreproducto;
    private javax.swing.JLabel jLblIngresarPrecioProducto;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPnlBusquedaProducto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTPproductos;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTxtIDProducto;
    private javax.swing.JTable jtblProductos1;
    // End of variables declaration//GEN-END:variables
}
